### ISSUE TITLE
공용 Docs 환경 구축

### ISSUE THREAD

**Issue by robert-min** [C-auto/infra-lab#2]
### 🙋🏻‍♂️ 요구사항
- 팀 내부와 외부에 공유할 수 있는 환경을 구축
- 댓글 기능을 통해 피드백을 주고받을 수 있는 환경 제공(+댓글 메일 알림)
- 게시글에서 언급된 기술 스택이 태그로 구분될 수 있는 환경 필요
- 별도의 서버 구축이 아닌 Github에서 제공하는 환경을 최대한 활용

### 🧑‍💻 Todo
- [x] git에서 배포 가능한 Docs 환경 리서치 [#issue](https://github.com/C-auto/infra-lab/issues/2#issuecomment-1654945447)
  - [x] 댓글 기능
  - [x] 기술 스택 별 태그 적용
  - [x] 댓글 사용자 멘션 시 메일 전송 적용
  - [x] Docs 디자인
- [x] gitbook 환경 구축
  - [x] gitbook 연동을 위한 github repo 생성(share-docs)
  - [x] gitbook 계정 생성
  - [x] gitbook-github 연동
  - [x] gitbook 작성 테스트

**Comment by robert-min** [comment]
# Gitbook-Github 연동을 통한 공용 Docs 환경 구축

## GitBook
- (공식문서)제품에서 내부 지식 기반 및 API에 이르기까지 모든 것을 문서화 할 수 있는 최신 문서 플랫폼
- Github 연동을 통한 체계적인 관리와 기존 깃허브 사용에 익숙한 개발자에게 편리하게 적용 가능

### 요구사항 적용
1. 기술 스택 별 태그 적용
  - Gitbook 게시글 안에서 기술 스택별 태그를 통해 관리하는 기능은 현재 찾지 못했지만 메인 기술스택별 폴더를 분리하여 관리하는 기능 확인
  - 기술 스택별 태그는 PR 요청할 때 label을 추가하는 방향으로 하고 추후에 해당 기능 발견시 기능 추가
  - 별도로 검색기능 성능 확인이 필요하지만 필요한 태그 적용 없어도 검색 기능으로 대체 가능할 것으로 판단
2. 댓글 기능 + 댓글 사용자 멘션 시 메일 전송 적용
  - gitbook 안에서 disqus 적용을 통해 댓글 기능 적용이 가능하지만 댓글 작성자가 별도로 소셜 로그인이 필요하여 불편할 것으로 생각.
  - 추가로 댓글의 목적이 게시물을 배포하기 전 팀 내에서 서로 공유하는 피드백 목적이기 때문에 이미 배포된 gitbook에서 댓글을 다는 방식이 아닌 PR에서 댓글을 통해 질문하는 방식이 더 유용할 것으로 생각
  - PR에서 댓글을 달 경우 github 자체적으로 멘션 시 메일알림을 전송하기 때문에 댓글 작성 시 메일 전송 적용 기능도 추가로 구현할 필요 없음
3. Docs 디자인
  - gitbook 디자인 변경 가능 여부는 추가 확인이 필요하지만 현재는 기본 템플릿도 충분할 것으로 판단해 기본 템플릿으로 진행
